---
abstract: 'The Chinese sentence generator.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.023, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Lingua-ZH-Remix
provides:
  Acme::Lingua::ZH::Remix:
    file: lib/Acme/Lingua/ZH/Remix.pm
    version: '0.99'
requires:
  Hash::Merge: '0'
  List::MoreUtils: '0'
  Moo: '0'
  Types::Standard: '0'
resources:
  bugtracker: https://github.com/gugod/Acme-Lingua-ZH-Remix/issues
  homepage: https://github.com/gugod/Acme-Lingua-ZH-Remix
  repository: git://github.com/gugod/Acme-Lingua-ZH-Remix.git
version: '0.99'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
