---
abstract: 'The Chinese sentence generator.'
author:
  - ',2011,2012 by Kang-min Liu, <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Lingua::ZH::Remix
name: Acme-Lingua-ZH-Remix
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0.12
  Hash::Merge: 0
  List::MoreUtils: 0
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: http://github.com/gugod/Acme-Lingua-ZH-Remix.git
version: 0.96
